
--DDL Scripts

create or replace TABLE TEST.PUBLIC.CONTRACTORS (
	CONTRACTOR_NAME STRING,
	CONTRACTOR_ID STRING,
	STREET STRING,
	CITY STRING,
	STATE STRING,
	ZIP STRING,
	SUBMITTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS TEST.PUBLIC.contract_activity_type (
    activity_id INT,
    activity_name STRING,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS TEST.PUBLIC.engagements (
    ENGAGEMENT_ID INT,
    contractor_id STRING,
    customer_name STRING,
    street STRING,
    city STRING,
    state STRING,
    zip_code STRING,
    engagement_type STRING,
    activity_date DATE,
    rating INTEGER,  -- ⭐ New field
    feedback STRING,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
--PK
ALTER TABLE TEST.PUBLIC.ENGAGEMENTS ALTER COLUMN ENGAGEMENT_ID SET NOT NULL;
ALTER TABLE TEST.PUBLIC.ENGAGEMENTS ADD PRIMARY KEY (ENGAGEMENT_ID);

-- 1. Create a sequence
CREATE OR REPLACE SEQUENCE ENGAGEMENT_ID_SEQ START = 1 INCREMENT = 1;
-- 2. Add a new column
-- ALTER TABLE TEST.PUBLIC.ENGAGEMENTS ADD COLUMN ENGAGEMENT_ID INT;
-- ALTER TABLE çengagements ADD COLUMN rating INTEGER;

-- 3. Populate it
-- UPDATE TEST.PUBLIC.ENGAGEMENTS SET ENGAGEMENT_ID = ENGAGEMENT_ID_SEQ.NEXTVAL WHERE ENGAGEMENT_ID IS NULL;

DROP TABLE IF EXISTS TEST.PUBLIC.subscription;
CREATE TABLE IF NOT EXISTS TEST.PUBLIC.subscription (
    subscription_id INT,
    subscription_months INT,
    subscription_amt_usd FLOAT,
    subscription_activated_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS TEST.PUBLIC.users;
CREATE TABLE IF NOT EXISTS TEST.PUBLIC.users (
    username STRING PRIMARY KEY,
    hashed_password STRING,
    full_name STRING,
    password_raw STRING,
    member_expiration_date TIMESTAMP,
    member_email STRING,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

