
--DDL Scripts
DROP TABLE IF EXISTS DEV.PUBLIC.CONTRACTORS;
CREATE or REPLACE TABLE DEV.PUBLIC.CONTRACTORS (
	CONTRACTOR_NAME STRING,
	CONTRACTOR_ID STRING,
	STREET STRING,
	CITY STRING,
	STATE STRING,
	ZIP STRING,
	SUBMITTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS DEV.PUBLIC.contract_activity_type;
CREATE TABLE IF NOT EXISTS DEV.PUBLIC.contract_activity_type (
    activity_id INT,
    activity_name STRING,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS DEV.PUBLIC.engagements;
CREATE TABLE IF NOT EXISTS DEV.PUBLIC.engagements (
    ENGAGEMENT_ID INT,
    contractor_id STRING,
    customer_name STRING,
    street STRING,
    city STRING,
    state STRING,
    zip_code STRING,
    engagement_type STRING,
    activity_date DATE,
    rating INTEGER,  -- ⭐ New field
    feedback STRING,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
--PK
ALTER TABLE DEV.PUBLIC.ENGAGEMENTS ALTER COLUMN ENGAGEMENT_ID SET NOT NULL;
ALTER TABLE DEV.PUBLIC.ENGAGEMENTS ADD PRIMARY KEY (ENGAGEMENT_ID);


DROP TABLE IF EXISTS DEV.PUBLIC.subscription;
CREATE TABLE IF NOT EXISTS DEV.PUBLIC.subscription (
    subscription_id INT,
    subscription_months INT,
    subscription_amt_usd FLOAT,
    subscription_activated_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS DEV.PUBLIC.users;
CREATE TABLE IF NOT EXISTS DEV.PUBLIC.users (
    username STRING PRIMARY KEY,
    hashed_password STRING,
    full_name STRING,
    password_raw STRING,
    member_expiration_date TIMESTAMP,
    member_email STRING,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

--Sequences
DROP SEQUENCE IF EXISTS DEV.PUBLIC.ENGAGEMENT_ID_SEQ;
CREATE OR REPLACE SEQUENCE DEV.PUBLIC.ENGAGEMENT_ID_SEQ 
    START WITH 1 
    INCREMENT BY 1;

DROP SEQUENCE IF EXISTS DEV.PUBLIC.contractor_seq;
CREATE OR REPLACE SEQUENCE DEV.PUBLIC.contractor_seq
    START WITH 1
    INCREMENT BY 1; 